PointyPointy/Models/InviteViewModel.cs
namespace PointyPointy.Models
{
    public class InviteViewModel : BaseViewModel
    {
        
    }
}

PointyPointy/ViewModels/InviteViewModel.cs
namespace PointyPointy.ViewModels
{
    public class InviteViewModel : BaseViewModel
    {
        
    }
}

PointyPointy/Controllers/InviteController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using PointyPointy.Data;
using PointyPointy.Data.Entities;
using PointyPointy.Models;
using PointyPointy.Services;
using PointyPointy.ViewModels;

namespace PointyPointy.Controllers
{
    public class InviteController : Controller
    {
        private readonly IScrumInviteService _scrumInviteService;

        public InviteController(IScrumInviteService scrumInviteService)
        {
            _scrumInviteService = scrumInviteService;
        }

        // GET: Invite
        [Authorize]
        public ActionResult Index(InviteViewModel vm)
        {
            return View(vm);
        }

        // GET: Invite/Create
        [Authorize]
        public ActionResult Create()
        {
            var vm = new InviteCreateViewModel();

            return View(vm);
        }

        // POST: Invite/Create
        [HttpPost]
        [Authorize]
        [ActionName("Create")]
        public ActionResult CreatePOST(InviteCreateViewModel vm)
        {
            var invitees = vm.Invitees.Split(new[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries);

            if (invitees.Length == 0)
            {
                ModelState.AddModelError("Invitees", "You need at least one email address to invite.");

                return View("Create", vm);
            }

            var inviteResponse = _scrumInviteService.CreateInviteForUsers(vm.User, invitees);

            if (!inviteResponse.Success)
            {
                ModelState.AddModelError("Invitees", "Well that's embarrassing, something went wrong.");

                return View("Create", vm);
            }

            return RedirectToAction("Created", new { id = inviteResponse.Response.Id });
        }

        [Authorize]
        public ActionResult Created(InviteCreatedViewModel vm)
        {
            var inviteResponse = _scrumInviteService.GetById(vm.Id);

            if (inviteResponse.Response.UserId != vm.User.Id)
            {
                return new HttpUnauthorizedResult();
            }

            return View(vm);
        }

        // GET: Invite/Respond
        public ActionResult Respond(InviteRespondViewModel vm)
        {
            /// TODO: Handle Response.Success == false
            vm.InviteUser = _scrumInviteService.GetInviteUserForKey(vm.Key, vm.Email).Response;

            return View(vm);
        }

        // POST: Invite/Response
        [HttpPost]
        public ActionResult Respond(InviteResponseViewModel vm)
        {
            /// TODO: Handle Response.Success == false
            vm.InviteUser = _scrumInviteService.Respond(vm.Id, vm.Email, vm.Key, vm.Accept).Response;

            return View(vm);
        }
    }
}

PointyPointy/Views/Invite/Create.cshtml
@model PointyPointy.ViewModels.InviteCreateViewModel

<h1>Lets get started!</h1>

<p class="lead">We'll need a list of the people who you want to take part in the scrum. We will email them to ask them to register and then you can start pointing.</p>
<p class="small text-muted">Don't worry, we won't bombard them with emails or anything like that, in fact if they register through a thrid party then we won't even know their password.</p>

@using (Html.BeginForm("Create", "Invite"))
{
    <fieldset>
        <legend>Invite some people</legend>
        <div class="form-group">
            @Html.LabelFor(m => m.Invitees, new { @class = "sr-only" })
            <textarea id="Invitees" name="Invitees" class="form-control"></textarea>
            <p class="help-block">Put each email address on a separate line.</p>
        </div>

        <button type="submit" class="btn btn-primary"><i class="fa fa-user-plus"></i> Invite</button>
    </fieldset>
}

PointyPointy/Views/Invite/Created.cshtml
@model PointyPointy.ViewModels.InviteCreatedViewModel

<h2>Invitation sent</h2>

<p>Invitations sent to:</p>

<ul>
    @foreach (var i in Model.ScrumInvite.Users)
    {
        <li>@i.Email</li>
    }
</ul>

PointyPointy/Views/Invite/Index.cshtml
@model PointyPointy.ViewModels.InviteViewModel

PointyPointy/Views/Invite/Response.cshtml
@model PointyPointy.ViewModels.InviteResponseViewModel

<h2>Accepted: @Model.Accept</h2>